### ISSUE TITLE
Double page numbers

### ISSUE THREAD

**Issue by aprilnovak** [emerzari/incite2022#6]
There's two sets of page numbers on each page - I'm not sure where this is happening in the Latex. I'm making a note of it here as a reminder to fix.

**Comment by hapfang** [comment]
I think the two sets of page numbers are caused by the fact that the sections are individually compiled first and then combined together as a single PDF. The pages are numbered multiple times in the process. If we can find a way to disable the numbering until the final assembling, it should fix the issue. I will look into it.

**Comment by emerzari** [comment]
Don’t disable the numbering. The proposal is uploaded one file at a time.


On Jun 17, 2021, at 12:52 PM, Jun Fang ***@***.***> wrote:

﻿

I think the two sets of page numbers are caused by the fact that the sections are individually compiled first and then combined together as a single PDF. The pages are numbered multiple times in the process. If we can find a way to disable the numbering until the final assembling, it should fix the issue. I will look into it.

**Comment by hapfang** [comment]
OK, got it.

**Comment by aprilnovak** [comment]
My mistake, I thought `proposal.pdf` would be submitted. Closing because non-issue
